package edu.univ.erp.domain;

public enum Task
{
    LOGIN,
    ADD_USER,
    DELETE_USER,
    CREATE_COURSE,
    EDIT_COURSE,
    CREATE_SECTION,
    EDIT_SECTION,
    ASSIGN_INSTRUCTOR,
    TOGGLE_MAINTENANCE,
    COMPUTE_FINAL,
    ENTER_SCORES,
    SEE_MY_SECTIONS,
    SEE_CLASS_STATS,
    DROP_COURSES,
    REGISTER_FOR_COURSES,
    VIEW_TIMETABLE,
    VIEW_GRADES,
    DOWNLOAD_TRANSCRIPT,
    // add more
}
