package edu.univ.erp.domain;

public enum Task
{
    LOGIN,
    VIEW_COURSE,
    ADD_USER,
    DELETE_USER,
    CREATE_COURSE,
    UPDATE_COURSE,
    DELETE_COURSE,
    CREATE_SECTION,
    UPDATE_SECTION,
    DELETE_SECTION,
    ASSIGN_INSTRUCTOR,
    TOGGLE_MAINTENANCE,
    COMPUTE_FINAL,
    ENTER_SCORES,
    SEE_MY_SECTIONS,
    SEE_CLASS_STATS,
    DROP_COURSES,
    REGISTER_FOR_COURSES,
    VIEW_TIMETABLE,
    VIEW_GRADES,
    UPDATE_PROFILE,
}
